### ISSUE TITLE
Request to add our FSCIL paper

### ISSUE THREAD

**Issue by LinglanZhao** [zhoudw-zdw/Awesome-Few-Shot-Class-Incremental-Learning#2]
Thank you for your awesome repo!
Would you please add our CVPR 2023 paper 'Few-Shot Class-Incremental Learning via Class-Aware Bilateral Distillation'?
PDF link: https://openaccess.thecvf.com/content/CVPR2023/papers/Zhao_Few-Shot_Class-Incremental_Learning_via_Class-Aware_Bilateral_Distillation_CVPR_2023_paper.pdf
Code link: https://github.com/LinglanZhao/BiDistFSCIL

Thanks!

**Comment by zhoudw-zdw** [comment]
Sure, noted with thanks.
