### ISSUE TITLE
Request to add our FSCIL paper

### ISSUE THREAD

**Issue by ZHUANGHP** [zhoudw-zdw/Awesome-Few-Shot-Class-Incremental-Learning#3]
Can you add our paper in CVPR 23 "GKEAL: Gaussian Kernel Embedded Analytic Learning for Few-shot Class Incremental Task"? Thanks! (https://openaccess.thecvf.com/content/CVPR2023/html/Zhuang_GKEAL_Gaussian_Kernel_Embedded_Analytic_Learning_for_Few-Shot_Class_Incremental_CVPR_2023_paper.html)

**Comment by zhoudw-zdw** [comment]
Thanks.
